import { DailyTransactionType, DailyTransactionSource } from '@prisma/client';
import { PrismaClient } from '@prisma/client';
import { prisma } from '../../config/prisma';

/**
 * BELGE NO (ZORUNLU) - 3.1 & 3.2
 * 
 * Belge No asla boş olamaz
 * Backend: Create sırasında belgeNo yoksa otomatik üretir
 * Format: {PREFIX}-{DD/MM}-{SEQ}
 * 
 * Transferlerde: Aynı belgeNo kökü, IN/OUT satırları suffix ile ayrılabilir
 */

export type DocumentPrefix =
  | 'NKT-GRS' // Nakit Giriş (KASA)
  | 'NKT-CKS' // Nakit Çıkış (KASA)
  | 'BNK-GRS' // Banka Giriş
  | 'BNK-CKS' // Banka Çıkış
  | 'POS-GRS' // POS Giriş
  | 'POS-KOM' // POS Komisyon
  | 'KRD-ODM' // Kredi Kartı Ödeme
  | 'KRD-HRC' // Kredi Kartı Harcama
  | 'CEK-GRS' // Çek Giriş
  | 'CEK-CKS' // Çek Çıkış
  | 'TRF' // Transfer (kök)
  | 'DVR' // Devir Bakiye
  | 'DZT'; // Düzeltme

/**
 * Get document prefix for transaction type and source
 */
export function getDocumentPrefix(
  type: DailyTransactionType,
  source: DailyTransactionSource
): DocumentPrefix {
  switch (type) {
    case 'NAKIT_TAHSILAT':
      return source === 'KASA' ? 'NKT-GRS' : 'BNK-GRS';
    case 'NAKIT_ODEME':
      return source === 'KASA' ? 'NKT-CKS' : 'BNK-CKS';
    case 'BANKA_HAVALE_GIRIS':
      return 'BNK-GRS';
    case 'BANKA_HAVALE_CIKIS':
      return 'BNK-CKS';
    case 'POS_TAHSILAT_BRUT':
      return 'POS-GRS';
    case 'POS_KOMISYONU':
      return 'POS-KOM';
    case 'KREDI_KARTI_HARCAMA':
      return 'KRD-HRC';
    case 'KREDI_KARTI_EKSTRE_ODEME':
      return 'KRD-ODM';
    case 'CEK_GIRISI':
      return 'CEK-GRS';
    case 'CEK_TAHSIL_BANKA':
      return source === 'KASA' ? 'CEK-GRS' : 'BNK-GRS';
    case 'CEK_ODENMESI':
      return source === 'KASA' ? 'CEK-CKS' : 'BNK-CKS';
    case 'CEK_KARSILIKSIZ':
      return 'CEK-CKS';
    case 'BANKA_KASA_TRANSFER_OUT':
    case 'BANKA_KASA_TRANSFER_IN':
    case 'KASA_BANKA_TRANSFER_OUT':
    case 'KASA_BANKA_TRANSFER_IN':
      return 'TRF';
    case 'DEVIR_BAKIYE':
      return 'DVR';
    case 'DUZELTME':
      return 'DZT';
    case 'KREDI_TAKSIT_ODEME':
      return source === 'BANKA' ? 'BNK-CKS' : 'NKT-CKS';
    default:
      // Fallback: use source-based prefix
      return source === 'BANKA' ? 'BNK-GRS' : 'NKT-GRS';
  }
}

/**
 * Generate document number: {PREFIX}-{DD/MM}-{SEQ}
 */
export function generateDocumentNo(
  prefix: DocumentPrefix,
  isoDate: string,
  seq: number
): string {
  const [y, m, d] = isoDate.split('-');
  const dd = (d ?? '01').padStart(2, '0');
  const mm = (m ?? '01').padStart(2, '0');
  const s = String(seq).padStart(4, '0');
  return `${prefix}-${dd}/${mm}-${s}`;
}

/**
 * Get next document number for a given prefix and date
 * Finds the highest sequence number for the prefix-date combination and increments it
 */
export async function getNextDocumentNo(
  prefix: DocumentPrefix,
  isoDate: string,
  excludeTransactionIds?: string[]
): Promise<string> {
  const [y, m, d] = isoDate.split('-');
  const dd = (d ?? '01').padStart(2, '0');
  const mm = (m ?? '01').padStart(2, '0');
  const base = `${prefix}-${dd}/${mm}-`;

  // Find all transactions with the same prefix-date pattern
  const where: any = {
    deletedAt: null,
    documentNo: {
      startsWith: base,
    },
  };

  // Exclude specific transaction IDs (for updates)
  if (excludeTransactionIds && excludeTransactionIds.length > 0) {
    where.id = {
      notIn: excludeTransactionIds,
    };
  }

  const transactions = await prisma.transaction.findMany({
    where,
    select: {
      documentNo: true,
    },
  });

  // Extract sequence numbers and find max
  let maxSeq = 0;
  for (const tx of transactions) {
    if (!tx.documentNo) continue;
    const suffix = tx.documentNo.slice(base.length);
    const seq = parseInt(suffix, 10);
    if (!Number.isNaN(seq)) {
      maxSeq = Math.max(maxSeq, seq);
    }
  }

  return generateDocumentNo(prefix, isoDate, maxSeq + 1);
}

/**
 * Auto-generate document number for a transaction
 * BELGE NO (ZORUNLU) - 3.1: Belge No asla boş olamaz
 */
export async function autoGenerateDocumentNo(
  type: DailyTransactionType,
  source: DailyTransactionSource,
  isoDate: string,
  existingDocumentNo?: string | null,
  excludeTransactionIds?: string[]
): Promise<string> {
  // If documentNo is already provided, use it
  if (existingDocumentNo && existingDocumentNo.trim()) {
    return existingDocumentNo.trim();
  }

  // Generate new document number
  const prefix = getDocumentPrefix(type, source);
  return getNextDocumentNo(prefix, isoDate, excludeTransactionIds);
}

/**
 * Generate document number for transfer transactions
 * BELGE NO (ZORUNLU) - 3.2: Transferlerde aynı belgeNo kökü, IN/OUT satırları suffix ile ayrılabilir
 */
export async function generateTransferDocumentNo(
  isoDate: string,
  existingDocumentNo?: string | null,
  suffix?: 'IN' | 'OUT'
): Promise<string> {
  // If documentNo is already provided, add suffix if needed
  if (existingDocumentNo && existingDocumentNo.trim()) {
    const base = existingDocumentNo.trim();
    if (suffix) {
      return `${base}-${suffix}`;
    }
    return base;
  }

  // Generate new transfer document number
  const prefix = 'TRF';
  const base = await getNextDocumentNo(prefix, isoDate);
  if (suffix) {
    return `${base}-${suffix}`;
  }
  return base;
}

